# Generated by Django 4.1.6 on 2023-02-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('img_url', models.CharField(max_length=200)),
                ('rating', models.FloatField(null=True)),
                ('price', models.IntegerField()),
                ('actual_price', models.IntegerField()),
                ('discount', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
