# Generated by Django 4.1.6 on 2023-02-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='yello', max_length=100),
            preserve_default=False,
        ),
    ]
